name: 'Aggregate Alerts'
description: 'Aggregate alerts that are being sent to slack'

branding:
  icon: 'alert-circle'
  color: 'purple'

inputs:
  since:
    description: 'Beginning of the aggregation period. RFC3339 compliant date format.'
    required: false
  until:
    description: 'End of the aggregation period. RFC3339 compliant date format.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SINCE: ${{ inputs.since }}
    UNTIL: ${{ inputs.until }}
