name: 'Aggregate Alerts'
description: 'Aggregate alerts that are being sent to slack'

branding:
  icon: 'alert-circle'
  color: 'purple'

inputs:
  get-channnel-id:
    description: 'Slack channel id to aggregate alerts from'
    required: true
  send-channnel-id:
    description: 'Slack channel id to send aggregated results'
    required: false
  since:
    description: 'Beginning of the aggregation period'
    required: false
  until:
    description: 'End of the aggregation period'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GET_CHANNEL_ID: ${{ inputs.get-channnel-id }}
    SEND_CHANNEL_ID: ${{ inputs.send-channnel-id }}
    SINCE: ${{ inputs.since }}
    UNTIL: ${{ inputs.until }}
