on:
  push:
    branches:
      - main

jobs:
  aggregate-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          get-channnel-id: 'C069MM8H0EN'
